name: Deploy to DigitalOcean Docker Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker CLI
      uses: docker/setup-buildx-action@v2

    - name: Deploy to DigitalOcean
      run: |
        ssh -o StrictHostKeyChecking=no user@your-digitalocean-ip << 'EOF'
        docker pull your-docker-image
        docker stop your-container || true
        docker rm your-container || true
        docker run -d --name your-container -p 80:80 your-docker-image
        EOF

